from __future__ import annotations

import sys
from datetime import date, datetime, timedelta, timezone

import click
from flask.cli import with_appcontext
from sqlalchemy import and_, asc, desc, func, not_, or_, select, text


def discover_models(db) -> dict:
    models: dict = {}

    # SQLAlchemy >= 1.4 (registry API)
    registry = getattr(db.Model, "registry", None)
    if registry is not None:
        for mapper in registry.mappers:
            cls = mapper.class_
            models[cls.__name__] = cls
        return dict(sorted(models.items()))

    # Fallback SQLAlchemy < 1.4
    legacy = getattr(db.Model, "_decl_class_registry", {})
    for _name, cls in legacy.items():
        if isinstance(cls, type):
            models[cls.__name__] = cls
    return dict(sorted(models.items()))


def build_context(app, db) -> dict:
    models = discover_models(db)

    def commit():
        try:
            db.session.commit()
            print("✔ commit")
        except Exception as exc:  # noqa: BLE001
            db.session.rollback()
            print(f"✘ rollback — {exc}")

    def rollback():
        db.session.rollback()
        print("↩ rollback")

    ctx: dict = {
        "app": app,
        "db": db,
        "session": db.session,
        # Auto-discover models
        **models,
        # Frequent utilities
        "datetime": datetime,
        "date": date,
        "timedelta": timedelta,
        "timezone": timezone,
        "func": func,
        "select": select,
        "text": text,
        "and_": and_,
        "or_": or_,
        "not_": not_,
        "desc": desc,
        "asc": asc,
        # Helpers
        "commit": commit,
        "rollback": rollback,
    }
    ctx["_models"] = models
    return ctx


def build_banner(ctx: dict) -> str:
    model_names: str = ", ".join(ctx["_models"]) or "(none found)"
    return (
        "\n"
        "Flask shell-plus\n"
        f"Models: {model_names}\n"
        "Extras : db, session, func, select, and_, or_, desc, asc, datetime, date, timedelta, text\n"
        "Helpers: commit(), rollback()\n" + "─" * 30 + "\n"
    )


def init_shell_plus(app, db) -> None:

    @app.shell_context_processor
    def _auto_context():
        return build_context(app, db)

    @app.cli.command(
        "shell-plus", short_help="Interactive shell with auto-imported models."
    )
    @click.option(
        "--plain",
        is_flag=True,
        help="Use the standard Python shell even if IPython is installed.",
    )
    @click.option(
        "--print-sql", is_flag=True, help="Displays the SQL generated by each query"
    )
    @with_appcontext
    def shell_plus(plain: bool, print_sql: bool) -> None:
        ctx = build_context(app, db)
        banner = build_banner(ctx)

        if print_sql:
            db.engine.echo = True

        if not plain:
            try:
                from IPython import start_ipython
                from traitlets.config import Config

                config = Config()
                config.TerminalInteractiveShell.banner1 = banner
                config.TerminalInteractiveShell.enable_tip = False
                config.InteractiveShellApp.exec_lines = [
                    "%load_ext autoreload",
                    "%autoreload 2",
                ]
                start_ipython(argv=[], user_ns=ctx, config=config)
                return
            except ImportError:
                print("IPython is not installed (pip install ipython);\n")

        import code
        import readline  # noqa: F401
        import rlcompleter

        readline.set_completer(rlcompleter.Completer(ctx).complete)
        readline.parse_and_bind("tab: complete")
        code.interact(banner=banner, local=ctx)
        sys.exit(0)
